### ISSUE TITLE
Splitting up the main lessons repository

### ISSUE THREAD

**Issue by ethanwhite** [datacarpentry/datacarpentry#117]
We are planning on splitting up the main lessons repository, following Software Carpentry's lead in storing the material for each lesson in its own repo. The goal is to make maintaining and keeping track of individual lessons easier. The tentative plan is to maintain all of the history and split each top level folder in the `lessons` directory out into it's own repository. If there are objections to this change or ideas for improving the approach, let's talk about them here.

## To Do

- [x] Excel
- [x] Shell
- [x] SQL
- [x] R
- [x] Python
- [x] RNAseq
- [x] Scripting
- [x] Social Sciences Text Mining
- [x] Tidy Data

**Comment by wking** [comment]
On Fri, Feb 06, 2015 at 08:13:30AM -0800, Ethan White wrote:
> We are planning on splitting up the main lessons repository,
> following Software Carpentry's lead…

I'm not sure how much the Data Carpentry lessons overlap with the
Software Carpentry lessons, but I expect they could just share basic
stuff like the shell lesson (it looks like the bc stuff seeded the
datacarpentry shell lesson in 9aa13270, and subsequent updates
shouldn't be too hard to push upstream to swcarpentry/shell-novice…).

In any case, my history extraction notes for bc's shell lesson are
summarized in swcarpentry/shell-novice#2 if folks want to see how that
extraction went, and I'm happy to talk folks through the Git
manipulations if anyone wants (just @mention me in an issue or ping
`wking` on #sciencelab).

**Comment by ethanwhite** [comment]
Thanks @wking, I'll definitely take advantage of your generous offer to help out with the git-fu. I've already been using your notes as a starting point.

Regarding the lesson overlap, some of the Data Carpentry lessons did fork directly off of the lessons in bc, but I think the goal is for them to move away from the current SWC material both in terms of domain specificity and in terms of different emphasis on what is being taught.

**Comment by wking** [comment]
On Fri, Feb 06, 2015 at 09:10:36AM -0800, Ethan White wrote:
> Regarding the lesson overlap, some of the Data Carpentry lessons did
> fork directly off of the lessons in bc, but I think the goal is for
> them to move away from the current SWC material both in terms of
> domain specificity and in terms of different emphasis on what is
> being taught.

In that case, it may be easiest to take the associated SWC lesson
repository as a starting point, and just graft the DC changes on top
of wherever the DC lesson branched off.  That way you get the history
up to the fork point for free, and only have to worry about extracting
the DC-specific work.

**Comment by ethanwhite** [comment]
> In that case, it may be easiest to take the associated SWC lesson repository as a starting point, and just graft the DC changes on top of wherever the DC lesson branched off.

OK, that could work for the relevant lessons. Can you walk me through how that would work?

**Comment by cboettig** [comment]
:+1: Awesome. I think more modular repositories would be a big boon for future development of the lessons.

**Comment by drlabratory** [comment]
+1, will we be starting/grafting SWC's Sql materials? I liked creating the db part from DC lesson, but SWC has more examples of JOINs and GROUP BY

**Comment by ethanwhite** [comment]
> will we be starting/grafting SWC's Sql materials

The plan here is just to split up the existing repositories as is. If possible, we will bring in the history from SWC in cases where the material forked directly. This is not the case for the SQL material (well, I "forked it" off of how Greg taught live from way back before the v5 SWC materials). If there's material from the SWC SQL lessons that you'd like to see added then I think those would need to come in as PRs following the split.

One of the advantages to splitting it makes it easier to switch to a totally different way of teaching a particular set of material, because it can be proposed via a separate repo. So, in this case, if you thought that the current SWC SQL material provided a better starting point, you could create a new repo with the SWC history, customize it to fit with the datasets of one or more of the Data Carpentry domains, and propose that we make the switch.

**Comment by ethanwhite** [comment]
It looks like we're finally down to only one lessons worth of materials to split out before we're done. That lesson is the R lesson and I will start to tackle that once we get a clearer idea of the original history of that lesson and whether or not it was originally forked from the Software Carpentry R lesson (and therefore would need to have that history pulled in as well. See #139.
