### ISSUE TITLE
Naming conventions for split out repositories

### ISSUE THREAD

**Issue by ethanwhite** [datacarpentry/datacarpentry#118]
Assuming that we go forward with #117, we will need to figure out to handle repository naming. Given our domain specific focus this will include potentially 3 pieces of information: domain (e.g., ecology, genomics), topic (e.g., shell, Python, SQL), and level (novice, intermediate).

We could keep different levels of material together in the same repo. We don't have much intermediate material at the moment and the development of this material has been slow in SWC. Novice vs intermediate material could simply be deliniated within each repo with material for (for example) a novice workshop clearly identified. This would reduce the number of repositories to a more manageable level and we can always split levels later if it becomes necessary/desirable.

So, I'll throw out an initial recommendation of topic-domain, e.g., `sql-ecology` coming back to deal with level later if necessary.

Thoughts?

**Comment by emhart** [comment]
My only thought with topic-domain is that of the three elements of naming convention, domain probably has the highest likelihood for proliferation.  I doubt we'll have more than three classes of levels, and I doubt that a large number of new topics will be added, but it's easy to see as DC grows, it will add collaborators who come from a variety of disciplines who might adapt the curriculum.  Then you might end up with something like:
- `sql-ecology`
- `sql-genomics`
- `sql-paleontology`
- `sql-macroeconomics`
- `sql-libriaries`
- `sql-evolution`

etc...  So I just wonder if it might become unwieldy in the future.  Just a thought, perhaps that's trying to solve a problem that doesn't exist, but it might be worth considering.

**Comment by gvwilson** [comment]
Software Carpentry r-novice-thingy, where 'thingy' is the particular 
example (e.g., the inflammation dataset).  I now think that 'novice' vs. 
'intermediate' isn't the right terminology: what we really want is 
'moves slowly for people who have never seen this before' vs. 'moves 
quickly for people who are familiar with the ideas but not in this form' 
(e.g., a lesson on R for Python programmers or vice versa).

**Comment by tracykteal** [comment]
What about levels rather than specific names? So, 'level1', 'level2'. That could imply that the speed are at different levels or that the content in level2 would build off of the knowledge in level1. That would let some topics get pretty advanced, say 'level5' while others might only have a 'level1' if that is all that's necessary. 

We could also then frame it as 'leveling up' a set of lessons if we wanted a more advanced set of materials, rather than targeting a particular type of learner.

**Comment by ethanwhite** [comment]
@emhart - I'm not sure how to get around the large number of repositories issue. Whether it's sql-ecology or ecology-sql it's still the same number of repos (i.e., these aren't nested in any way). In general I think that lots of small repos is more manageable than a few big ones (per SWC's experience).

@gvwilson & @tracykteal - it sounds to me like we're not super clear on what we be going in these different levels. I'm personally not super keen on this distinction as being the same thing but faster vs slower. So this might require another level of conversation about what we'd be hoping to accomplish with different levels. Do either of you see a compelling reason for tackling the levels thing now vs. waiting to see how the material develops and then renaming things if necessary?

**Comment by gvwilson** [comment]
> @gvwilson <https://github.com/gvwilson> & @tracykteal 
> <https://github.com/tracykteal> - it sounds to me like we're not super 
> clear on what we be going in these different levels. I'm personally 
> not super keen on this distinction as being the same thing but faster 
> vs slower. So this might require another level of conversation about 
> what we'd be hoping to accomplish with different levels. Do either of 
> you see a compelling reason for tackling the levels thing now vs. 
> waiting to see how the material develops and then renaming things if 
> necessary?
>
No compelling reason to tackle levels now.

**Comment by tracykteal** [comment]
Agree no need to tackle level now.

**Comment by hlapp** [comment]
Given that we've been creating split out lesson repos according to a naming convention, I think we've essentially decided this for now, right? If someone strongly disagrees, please reopen, but I'm going to close this for now.
