### ISSUE TITLE
develop a basic statistics lesson

### ISSUE THREAD

**Issue by fmichonneau** [datacarpentry/datacarpentry#126]
it might be worth developing a lesson that show how to do basic statistical analyses (ANOVA, ANCOVA, linear regressions) in R (and python).

**Comment by hlapp** [comment]
This issue was moved to datacarpentry/test#1

**Comment by hlapp** [comment]
> This issue was moved to datacarpentry/test#1

Except this was only for testing, so really it wasn't.

**Comment by hlapp** [comment]
This issue was moved to datacarpentry/planning#9
