### ISSUE TITLE
Data missing from split-out lesson repos

### ISSUE THREAD

**Issue by hlapp** [datacarpentry/datacarpentry#141]
The question about where to put (and thus from where to get within a lesson) the data set needs to be re-determined. Originally, there was to be a `data/` directory in the main lesson repo, but that doesn't seem to have come along when splitting out lessons, and so now it's not clear where the data goes.

**Comment by ethanwhite** [comment]
The data is now available externally via figshare:
http://figshare.com/articles/Portal_Project_Teaching_Database/1314459

I think we should move all lessons to accessing the data directly from there.

**Comment by hlapp** [comment]
> The data is now available externally via figshare:
> http://figshare.com/articles/Portal_Project_Teaching_Database/1314459

Good point. Should lessons start with a point-and-click download from there, or with a series of copy&paste `curl` commands?

**Comment by ethanwhite** [comment]
Given that this is novices I think point-and-click downloads are the way to go unless the lesson is specifically dealing with automating this sort of thing.

**Comment by hlapp** [comment]
This issue was moved to datacarpentry/planning#10
