### ISSUE TITLE
Making review of pending pull requests more efficient 

### ISSUE THREAD

**Issue by hlapp** [datacarpentry/datacarpentry#142]
The Data Carpentry steering committee members and its Project Lead have an ongoing responsibility to review, comment on, and, when ready, merge pull requests (PRs), in particular for lesson materials after they have been "released" (i.e., taught), to ensure consistency, good organization, and coherence of materials is maintained. Due to the "minimum-of-two-pairs-of-eyeballs" policy, these PRs will almost always not be one they submitted themselves, and with the lessons being split out each into their own repo, it can be quite difficult to know where to go and look for PRs that need reviewing. This is especially so if you're like me and you don't have the necessary block of time whenever one comes in.

One idea is to create a markdown page (in the wiki, or in the repo) that lists all lesson repos, each with a link to the list of PRs (such as [this](https://github.com/datacarpentry/datacarpentry/pulls) for this repo), and ideally the number of currently open PRs. This could conceivably be generated by a script at regular intervals, or one that gets triggered by means of webhooks.

Another idea could be to use some kind of round-robin principle for assigning incoming PRs, and then everyone looks at what's assigned to them. The round-robin assignments could also be scripted and automated through webhooks. (Though I would argue that assigning stuff risks turning people unnecessarily into points of failure.)

There are probably other ways to deal with. Thoughts anyone? Solutions by comparable projects (SWC??) that we could borrow from?

**Comment by ethanwhite** [comment]
You can get the full list of PRs for the org with a specially constructed url. I think this is probably right:
https://github.com/pulls?q=is%3Aopen+is%3Aissue+user%3Adatacarpentry

Thanks to @gvwilson for doing the hard work of figuring this out for Software Carpentry.

**Comment by ethanwhite** [comment]
Just added this to my bookmark bar :) Very handy.

**Comment by hlapp** [comment]
> You can get the full list of PRs for the org with a specially constructed url. I think this is probably right:
> https://github.com/pulls?q=is%3Aopen+is%3Aissue+user%3Adatacarpentry
> 
> Thanks to @gvwilson for doing the hard work of figuring this out for Software Carpentry.

Super cool!

**Comment by wking** [comment]
On Sat, Mar 28, 2015 at 12:26:16PM -0700, Ethan White wrote:
> You can get the full list of PRs for the org with a specially
> constructed url. I think this is probably right:
> https://github.com/pulls?q=is%3Aopen+is%3Aissue+user%3Adatacarpentry

GitHub seems to redirect that intelligently (so it works), but it should be:

  https%3A//github.com/pulls?q=is%3Aopen+is%3Apr+user%3Adatacarpentry

(with is:pr instead of is:issue).  For lots of other fun issue- and
PR-sorting syntax, see [1].

[1]: https://help.github.com/articles/searching-issues/

**Comment by ethanwhite** [comment]
Thanks @wking! I'd figured that wasn't right, but I had tried `:pull` and a couple of other versions and hadn't gotten it to work. Thanks for the link to the docs page.

**Comment by ethanwhite** [comment]
Looks like this solves @hlapp's issue so closing.
