### ISSUE TITLE
Link to split lessons

### ISSUE THREAD

**Issue by jezcope** [datacarpentry/datacarpentry#143]
Is it worth using this repo to collect links to the split-out lessons, either using `git submodule` (though that's confusing for beginners) or just updating `README.md`?

**Comment by ethanwhite** [comment]
I think we definitely want a list and updating the README in this repo would be a good way to handle that (submodules seem like overkill to me).

**Comment by jezcope** [comment]
Yes, submodules do seem overkill — my vote would be with updating the README too, especially as the "Material" link from the DC website currently links straight through to that README.

**Comment by ethanwhite** [comment]
Definitely. Any chance you have a few minutes to submit a PR?
