### ISSUE TITLE
Need to add attributions for origins of shell, shell scripting, and SQL lessons

### ISSUE THREAD

**Issue by hlapp** [datacarpentry/datacarpentry#25]
This is in the CONTRIBUTORS.md file. Shell and shell scripting probably share the same origin (shell scripting lessons on SWC).

Should also add attribution entries for lessons newly added at the sprint.

**Comment by ethanwhite** [comment]
With no objections in 8 months I think this has been sitting long enough to be closed :) If there are still concerns about the scripting lessons those concerns should be reopened in:
https://github.com/datacarpentry/scripting-ecology

**Comment by hlapp** [comment]
The attribution is in the commit message for datacarpentry/scripting-ecology@8cfd21788fc224281ead834e6008b47e0cd75fd5. I had left this open as a reminder to put a somewhat shorter version of this into the README.

**Comment by ethanwhite** [comment]
OK, re-opening. PR coming momentarily.

**Comment by hlapp** [comment]
Looks like we're good now. Thanks much @ethanwhite!
