### ISSUE TITLE
Process conversation from email

### ISSUE THREAD

**Issue by davclark** [datacarpentry/datacarpentry#4]
Thanks everyone and welcome Jonathan. Jonathan, I'm actually going to be out at Davis June 30th, July 1st and maybe July 2nd. Are you by any chance going to be around then? If so, maybe we could meet. Dav, if you're around then, maybe you would want to come out from Berkeley? Or I could maybe come out to Berkeley on the 2nd?

Right, Ben had mentioned moving the conversation to somewhere better for conversation. Since we don't have an explicit git respository for this yet, how about we start out with an etherpad? Then when we've identified issues we can create the social science lesson sections in github and track the issues related to those sections there.

So, here's an etherpad
https://datacarpentry.etherpad.mozilla.org/1
[the first datacarpentry etherpad! :) ]

The current Data Carpentry repository is here:
https://github.com/swcarpentry/datacarpentry/

We're organizing things in lessons, so right now we just have the main lessons that are for biology. We're thinking domain specific lessons could be labeled that way (and we should probably rename the main ones as 'biology').

So a social sciences text analysis lesson might be:

social-sciences-text-analysis-R

or if the R example will just be text analysis, it could be

social-sciences-R

and within the 'data' directory we can have the different data sets, so we'd have 

data/biology
data/social-sciences
etc.

Ben Marwick	June 19, 2014 at 3:39 PM
Hi Dav, 

Let's compare notes, I've proposed a lesson on 'Text analysis in R using tm for Data Carpentry' for the sprint (see line 60 on https://etherpad.mozilla.org/swc-sprint-2014). 

Ben Marwick	June 13, 2014 at 5:34 PM
Thanks for those URLs, yes, that resonates with the norms in my field, ASCII CSV is a standard archival format: http://www.tdar.org/why-tdar/preservation/ 

testdat (https://github.com/ropensci/testdat) might also have a role here 

Dav Clark	June 13, 2014 at 4:59 PM

I see fairly broad agreement that UTF-8 CSV, accompanied by appropriate metadata is the "best" solution for archival (ranging from the "established" folks like our own Jon Stiles to upstart techies like Open Knowledge Foundation). On metadata:

http://www.icpsr.umich.edu/icpsrweb/content/datamanagement/lifecycle/metadata.html
http://data.okfn.org/standards

So this is perhaps jumping the gun a bit, but I wanted to make sure we're thinking about the big picture (even if we're not teaching it). Here's a nice infographic [sic] for an overview:

http://www.icpsr.umich.edu/icpsrweb/content/deposit/guide/index.html

And here's some stuff I put together for the "Info-Energy Nexus":

https://github.com/infoEnergy/data/blob/master/CONCERNS.md

D

**Comment by ethanwhite** [comment]
With the move to the new - one repository per lesson - structure this is now closed.
