### ISSUE TITLE
Suggested dataset for Economics / Innovation / Macro

### ISSUE THREAD

**Issue by areff2000** [datacarpentry/datacarpentry#5]
1.For an Economics dataset, please consider the GDP data, by country by year from World Bank.

http://databank.worldbank.org/data/views/reports/tableview.aspx?isshared=true

2.For an innovation dataset, particularly to rank countries by Innovation, I would recommend mashing up GDP data with labour and capital data. 

2.1 Labour would be calculated by:
- population data
- participation data ie % of population in workforce
- may need to adjust for full time/part time.

2.2 Capital would be calculated by including:
- land value (but would have to remove overlap with capital). An issue would be whether to use historical or market values.
- capital value ie stockmarket  market values. These figures are easier to access but contain non-tangible components such as goodwill, people and processes.
An alternative is to use company tangible assets. In Australia they can be sourced from Tax Office data on data.gov.au.

2.3 A final important element / variable is the satisfaction of citizens. The GINI factors could be used which track distribution of income in a society. Other well-being indicators include OECD report on happiness (140 countries) (oecdbetterlifeindex.org). There are 11 indicators which you can adjust levels to form an aggregate index. [Global Sprint - Summer 14]

**Comment by hlapp** [comment]
This issue was moved to datacarpentry/planning#4
