### ISSUE TITLE
Lesson for 'keeping track of data analyses' and file versioning

### ISSUE THREAD

**Issue by tracykteal** [datacarpentry/datacarpentry#59]
Anuremburger suggested some text about keeping track of what analyses you did as a README and versioning data files. This could be expanded in to a short lesson.

**Comment by ethanwhite** [comment]
We need a new central repo of some sort to handle these sorts of issues as well as general organizational discussion. Maybe `planning`? Once we have one we should move all of the open `lesson wanted` issues there.

**Comment by tracykteal** [comment]
Good idea. I just created a 'lesson-template' repo for discussion of those issues, and ultimately a template lesson layout. There are a lot of other things like this that don't have categories yet though. I went ahead an created a 'planning' repo. https://github.com/datacarpentry/planning

**Comment by hlapp** [comment]
This issue was moved to datacarpentry/planning#5
