### ISSUE TITLE
Update lessons now that all datafiles in top level 'data' directory

### ISSUE THREAD

**Issue by kcranston** [datacarpentry/datacarpentry#69]
@jennybc @apawlik @cbahlai @tracykteal @benmarwick 
Can you review your lessons now that all of the data files are in a single top-level 'data' directory? Some of the paths may no longer work.

**Comment by ethanwhite** [comment]
I'm going to go ahead and close this. We'll need to revisit this issue again in a new way once we finish splitting this repo up into individual lessons.
