### ISSUE TITLE
Decide on conventions for file locations, naming, etc.

### ISSUE THREAD

**Issue by kcranston** [datacarpentry/datacarpentry#70]
I am super happy that people have contributed so many new lessons! Seems that we should decide on some conventions about where things go and put those in the CONTRIBUTING file. For example, we've decided that data files do not go in the lessons directory, but in the data directory - yay. Here are some questions I have:

* should data be organized by domain (i.e. 'biology') or lesson ('text-mining')?
* should a lesson about data cleaning using R go under lessons/R or lessons/data-cleaning?
* should we continue to have a single large repository or break this into smaller repos that are more specific?

Thoughts? other questions we should consider?

**Comment by hlapp** [comment]
Has this issue become obsolete by splitting out the lessons? It seems to me, but am not sure, so will leave open but would encourage someone to close as soon as there seems to be consensus on this.

**Comment by ethanwhite** [comment]
After some discussion on the mailing list, and using the basic style of Software Carpentry, we ended up going with tool-topic for naming the repos. So, I agree with @hlapp that this is obsolete and am going to go ahead and close it. Feel free to re-open if there are any objections.
