### ISSUE TITLE
create script to generate directory structure and 

### ISSUE THREAD

**Issue by fmichonneau** [datacarpentry/datacarpentry#90]
During the data carpentry workshop that took place at iDigBio we wasted a lot of time waiting to have everybody with a basic directory structure that contained the datasets needed for the R lesson.

It seems that we could create a simple bash script that the participants could execute and that would create the directory structure needed for the lesson and download the datasets needed in the correct directories.

This approach would be more lightweight than having people clone the entire repository (in particular given that we don't cover git during the workshops). The directory structure would also be easier to navigate as the data would be closer to their working directory, and less confusing as it would only contain the material needed for the workshop.

The main disadvantage I see with this approach, is that folder organization might actually be a skill we would like to cover, and the script might make it seem "magical" to at least some of the participants.

Thoughts? comments?

**Comment by acorpuz** [comment]
Learning to download from the command line should definitely be covered in the shell lessons. I believe that a shell script that sets everything up can be run to have a starting uniform environment, the script can be later studied to see how the "magic" works. Basic shell use will cover creating and navigating directories anyways.

As for the source of the material, could a local file server be a solution?

**Comment by ethanwhite** [comment]
We have now moved to storing the core data externally (e.g., [1]) and individual lessons are being adapted to address this general problem. Therefore, I'm going to go ahead and close this, but if anyone has any objections please feel free to reopen.

[1] http://figshare.com/articles/Portal_Project_Teaching_Database/1314459
