### ISSUE TITLE
Data visualization in ecology lesson

### ISSUE THREAD

**Issue by tracykteal** [datacarpentry/datacarpentry#96]
It would be nice to be able to do something a little more interesting for data visualization and plotting in the R-ecology lesson. Being able to do scatter plots in particular would be good. 

Talking with Francois one idea that came up was to pose the questions:
- Do desert plots that have more kangaroo rats (say species DH) have a lower average weight of the other mammals than plots that don't? So, we could have a scatterplot that had 'number of observed DH species' on one axis and 'average weight of non-DH mammals' on the other axis.
- Do desert plots that have more kangaroo rats have fewer other species present, with 'number of observed DH species' on one axis and 'number of other species' on the other axis.
This would involve subsetting subsets though, so is this confounding subsetting and plotting too much?

Another option would be to add a column of numerical data that we could plot against weight. 

Thoughts?

**Comment by hlapp** [comment]
This issue was moved to datacarpentry/planning#7
